src/Lexik/Bundle/TopOrFlopBundle/Entity/Media.php
<?php

namespace Lexik\Bundle\TopOrFlopBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class Media
 *
 * @package Lexik\Bundle\TopOrFlopBundle\Entity
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Lexik\Bundle\TopOrFlopBundle\Repository\MediaRepository")
 */
class Media
{
    /**
     * @var integer $id
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string $url
     *
     * @ORM\Column(name="url", type="string", length=255)
     *
     * @Assert\NotBlank()
     */
    private $url;

    /**
     * @var string $title
     *
     * @ORM\Column(name="title", type="string", length=255)
     *
     * @Assert\NotBlank()
     */
    private $title;

    /**
     * @var float $average
     *
     * @ORM\Column(name="average", type="float", nullable=true)
     */
    private $average;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(
     *     targetEntity="Lexik\Bundle\TopOrFlopBundle\Entity\Vote",
     *     mappedBy="media",
     *     cascade={"persist"}
     * )
     *
     * @Serializer\Exclude()
     */
    private $votes;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->votes = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set url
     *
     * @param  string $url
     * @return Media
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set title
     *
     * @param  string $title
     * @return Media
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set average
     *
     * @param float $average
     */
    public function setAverage($average)
    {
        $this->average = $average;
    }

    /**
     * Get average
     *
     * @return float
     */
    public function getAverage()
    {
        return $this->average;
    }

    /**
     * Add Vote
     *
     * @param Vote $vote
     */
    public function addVote(Vote $vote)
    {
        $vote->setMedia($this);
        $this->votes[] = $vote;

        $this->computeAverageScore();
    }

    /**
     * Get Votes
     *
     * @return ArrayCollection
     */
    public function getVotes()
    {
        return $this->votes;
    }

    /**
     * Calculate the average score of the media
     */
    public function computeAverageScore()
    {
        /**
         * @todo finish this later.
         */
        $this->average = 0;
    }

    /**
     * Average score formatted for display
     *
     * @return string
     */
    public function getDisplayedAverage()
    {
        return (null === $this->average) ? '-' : sprintf('%.1f', $this->average);
    }

    /**
     * Whether the user has already voted for this media or not
     *
     * @param  User $user
     *
     * @return boolean
     */
    public function hasUserAlreadyVoted(User $user)
    {
        foreach ($this->votes as $vote) {
            if ($vote->getUser() == $user) {
                return true;
            }
        }

        return false;
    }
}

src/Lexik/Bundle/TopOrFlopBundle/Controller/DefaultController.php
<?php

namespace Lexik\Bundle\TopOrFlopBundle\Controller;

use Lexik\Bundle\TopOrFlopBundle\Entity\Media;
use Lexik\Bundle\TopOrFlopBundle\Form\VoteType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;

/**
 * Class DefaultController
 *
 * @package Lexik\Bundle\TopOrFlopBundle\Controller
 */
class DefaultController extends Controller
{
    /**
     * @Route("/", name="index")
     *
     * @return Response
     */
    public function indexAction()
    {
        return $this->render('LexikTopOrFlopBundle:Default:index.html.twig', array(
            'name' => 'Lexik',
            'days' => array('monday', 'tuesday', 'wednesday', 'thursday', 'friday'),
            'html' => '<b>ce texte n\'est pas en gras!</b>',
        ));
    }

    /**
     * @Route("/show", name="show_random")
     *
     * @return RedirectResponse
     *
     * @throws NotFoundHttpException
     */
    public function showRandomMediaAction()
    {
        $media = $this->get('lexik_top_or_flop.media_manager')->getNextMedia();

        if (!$media instanceof Media) {
            throw $this->createNotFoundException('No Media found.');
        }

        return $this->redirect($this->generateUrl('show_media', array('id' => $media->getId())));
    }

    /**
     * @Route("/show/{id}", name="show_media")
     *
     * @param integer $id
     *
     * @return Response
     *
     * @throws NotFoundHttpException
     */
    public function showMediaAction($id)
    {
        $mediaManager = $this->get('lexik_top_or_flop.media_manager');

        $media = $mediaManager->getMedia($id);
        if ($media === null) {
            throw $this->createNotFoundException();
        }

        if (null !== $vote = $mediaManager->getNewVote($media)) {
            $form = $this->createForm(new VoteType(), $vote);
        }

        return $this->render('LexikTopOrFlopBundle:Default:show.html.twig', array(
            'media' => $media,
            'form'  => isset($form) ? $form->createView() : null,
        ));
    }

    /**
     * @Route("/vote/{id}", name="vote_media")
     * @Method({"POST"})
     *
     * @param Request $request
     * @param integer $id
     *
     * @return Response
     *
     * @throws NotFoundHttpException
     */
    public function voteMediaAction(Request $request, $id)
    {
        $mediaManager = $this->get('lexik_top_or_flop.media_manager');

        $media = $mediaManager->getMedia($id);
        if ($media === null) {
            throw $this->createNotFoundException();
        }

        $vote = $mediaManager->getNewVote($media);

        $form = $this->createForm(new VoteType(), $vote);

        $form->handleRequest($request);

        if ($form->isValid()) {
            // $vote is saved by Media cascade persist
            $media->addVote($vote);
            $this->get('doctrine.orm.entity_manager')->flush();

            $this->get('session')->getFlashBag()->add('success', 'Votre vote est enregistré');

            return $this->redirect($this->generateUrl('show_media', array(
                'id' => $media->getId(),
            )));
        }

        $this->get('session')->getFlashBag()->add('error', 'Une erreur est survenue');

        return $this->forward('LexikTopOrFlopBundle:Default:showMedia', array(
            'id' => $media->getId(),
        ));
    }

    /**
     * @Route("/tops", name="show_tops")
     *
     * @return Response
     */
    public function showTopsAction()
    {
        $tops = $this->get('doctrine.orm.entity_manager')
            ->getRepository('Lexik\Bundle\TopOrFlopBundle\Entity\Media')
            ->getTopMedias();

        return $this->render('LexikTopOrFlopBundle:Default:tops.html.twig', array(
            'tops'  => $tops,
        ));
    }

    /**
     * @Route("/flops", name="show_flops")
     *
     * @return Response
     */
    public function showFlopsAction()
    {
        $flops = $this->get('doctrine.orm.entity_manager')
            ->getRepository('Lexik\Bundle\TopOrFlopBundle\Entity\Media')
            ->getFlopMedias();

        return $this->render('LexikTopOrFlopBundle:Default:flops.html.twig', array(
            'flops' => $flops,
        ));
    }
}

src/Lexik/Bundle/TopOrFlopBundle/Resources/views/Default/flops.html.twig
{% extends "LexikTopOrFlopBundle::layout.html.twig" %}

{% block title 'Top or Flop - flops' %}

{% block content %}
    <h2>Les plus gros Flops</h2>
    {% for index, flop in flops %}
        {% include "LexikTopOrFlopBundle:Default:media_list.html.twig" with { 'media': flop } %}
        <br />
    {% endfor %}
{% endblock %}

src/Lexik/Bundle/TopOrFlopBundle/Resources/views/Default/index.html.twig
{% extends "LexikTopOrFlopBundle::layout.html.twig" %}

{% block title 'Top or Flop - accueil' %}

{% block content %}
    Bienvenue sur ToporFlops !
{% endblock %}

src/Lexik/Bundle/TopOrFlopBundle/Resources/views/Default/media_list.html.twig
<a href="{{ path('show_media', {'id': media.id}) }}">
    {{ media.title }}
</a>
- {{ media.displayedAverage }}/10
<i>({{ media.votes | length }} votes)</i>

src/Lexik/Bundle/TopOrFlopBundle/Resources/views/Default/show.html.twig
{% extends "LexikTopOrFlopBundle::layout.html.twig" %}

{% block title 'Top or Flop - média' %}

{% block content %}
    <h2>{{ media.title }}</h2>
    <p>
        <img src="{{ media.url }}" /><br />
        <b>Score:</b> {{ media.displayedAverage }}/10  <i>({{ media.votes | length }} votes)</i>
    </p>
    <hr />
    <p>
        {% if is_granted('ROLE_USER') %}
            {% if not media.hasUserAlreadyVoted(app.user) %}
                <b>Top ou Flop ? Votez !</b>
                {{ form_start(form, {'action': path('vote_media', {'id': media.id}), 'method': 'POST', 'class': 'form-horizontal'}) }}
                    {{ form_errors(form) }}
                    {{ form_widget(form.score) }}
                    {{ form_widget(form.save, {'label': 'Voter', 'attr': {'class': 'btn btn-primary'}}) }}
                {{ form_end(form) }}
            {% endif %}
        {% else %}
            <div class="alert alert-block">Vous devez être connecté pour voter.</div>
        {% endif %}
    </p>
{% endblock %}

src/Lexik/Bundle/TopOrFlopBundle/Resources/views/Default/tops.html.twig
{% extends "LexikTopOrFlopBundle::layout.html.twig" %}

{% block title 'Top or Flop - tops' %}

{% block content %}
    <h2>Classement des Tops</h2>
    {% for top in tops %}
        {% include "LexikTopOrFlopBundle:Default:media_list.html.twig" with { 'media': top } %}
        <br />
    {% endfor %}
{% endblock %}